### PR TITLE
RunFlowMarkLogic now uses trust manager from the controller service

### LINKED ISSUE #145: RunFlowML does not work when DHF app servers require SSL
When RunFlowML creates its connections to the DHF app servers, it is using the `SSLService` and `SSLHostnameVerifier` from the user's SSL service in NiFi, but it is not carrying over the `X509TrustManager`. Because of this, we run into this error:

Caused by: java.lang.RuntimeException: Unable to retrieve flow with name: CurateCustomerJSON; cause: User is not allowed to POST at /data-hub/5/data-services/flow/getFullFlow.sjs
        at com.marklogic.hub.impl.FlowManagerImpl.getFullFlow(FlowManagerImpl.java:156)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl.runFlow(FlowRunnerImpl.java:179)
        at org.apache.nifi.marklogic.processor.RunFlowMarkLogic.onTrigger(RunFlowMarkLogic.java:153)

There's a separate issue here to analyze as to why we get a message like this when the root cause is due to an SSL misconfiguration. I'll follow up on that in the Java Client project with a test case. 

For the NiFi connector, we need to carry over either the user's provided trust store or a "trust anything" trust store.

### PR DESCRIPTION
**Pull request by rjrudin**
Resolves #145 . This was an oversight when the controller was first implemented. 

Also addressed a deprecation; now using the public ClientAuth class.

### CODE REVIEW

File: nifi-marklogic-services/src/main/java/org/apache/nifi/marklogic/controller/DefaultMarkLogicDatabaseClientService.java [hunk 1]
```diff
@@ -199,14 +200,12 @@ protected DatabaseClientConfig buildDatabaseClientConfig(ConfigurationContext co
 
         final SSLContextService sslService = context.getProperty(SSL_CONTEXT_SERVICE).asControllerService(SSLContextService.class);
         if(sslService != null) {
-            final SSLContextService.ClientAuth clientAuth = determineClientAuth(context);
+            final ClientAuth clientAuth = determineClientAuth(context);
+            getLogger().info("Configuring SSL connection; client authentication: " + clientAuth);
```
Comment (BillFarber) [inline nifi-marklogic-services/src/main/java/org/apache/nifi/marklogic/controller/DefaultMarkLogicDatabaseClientService.java:204]: I don't know enough about the ClientAuth class - are we confident this won't print any sensitive data?

**Review by BillFarber — APPROVED** [review]

File: nifi-marklogic-services/src/main/java/org/apache/nifi/marklogic/controller/DefaultMarkLogicDatabaseClientService.java (hunk 1 above)
Comment (rjrudin) [reply nifi-marklogic-services/src/main/java/org/apache/nifi/marklogic/controller/DefaultMarkLogicDatabaseClientService.java:204]: It's an enum class with properties of "type" and "description"; the "toString" is actually pretty helpful as it includes both. Doesn't include any sensitive data, as it's just a type of authentication, not the authentication itself.
